# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ 'localhost:9090' ]


  - job_name: 'eureka-server'
      scrape_interval: 2s
      metrics_path: '/actuator/prometheus' ##prometheus endpoint
      static_configs:
        - targets: [ 'localhost:8761' ] ## host and port for your mis

  - job_name: 'authentication-service'
          scrape_interval: 2s
          metrics_path: '/actuator/prometheus' ##prometheus endpoint
          static_configs:
            - targets: [ 'localhost:8099' ] ## host and port for your mis

  - job_name: 'application-register-service'
          scrape_interval: 2s
          metrics_path: '/actuator/prometheus' ##prometheus endpoint
          static_configs:
            - targets: [ 'localhost:8098' ] ## host and port for your mis

  - job_name: 'assessment-service'
          scrape_interval: 2s
          metrics_path: '/actuator/prometheus' ##prometheus endpoint
          static_configs:
            - targets: [ 'localhost:8081' ] ## host and port for your mis
        #
  - job_name: 'trend-lab-service'
          scrape_interval: 2s
          metrics_path: '/actuator/prometheus' ##prometheus endpoint
          static_configs:
            - targets: [ 'localhost:8086' ] ## host and port for your mis

  - job_name: 'chatroom-service'
          scrape_interval: 2s
          metrics_path: '/actuator/prometheus' ##prometheus endpoint
          static_configs:
            - targets: [ 'localhost:8089' ] ## host and port for your mis
        #
#        - job_name: 'email-service'
#          scrape_interval: 2s
#          metrics_path: '/actuator/prometheus' ##prometheus endpoint
#          static_configs:
#            - targets: [ '172.31.39.175:8085' ] ## host and port for your mis
#
#        - job_name: 'post-service'
#          scrape_interval: 2s
#          metrics_path: '/actuator/prometheus' ##prometheus endpoint
#          static_configs:
#            - targets: [ '172.31.39.175:9093' ] ## host and port for your mis
#
#        - job_name: 'recommendation-service'
#          metrics_path: '/actuator/prometheus'
#          scrape_interval: 3s
#          static_configs:
#            - targets: [ '172.31.39.175:9093' ]
#
#        - job_name: 'resources-service'
#          metrics_path: '/actuator/prometheus'
#          scrape_interval: 3s
#          static_configs:
#            - targets: [ '172.31.39.175:8087' ]
#
#        - job_name: 'api-gateway'
#          metrics_path: '/actuator/prometheus'
#          scrape_interval: 3s
#          static_configs:
#            - targets: [ '172.31.39.175:8080' ]